$('.owl-carousel').owlCarousel({
    center:true,
    loop:true,
    margin:10,
    nav:true,
    autoplayHoverPause:true,
    smartSpedd:1500,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:3
        }
    }
})
